import os
import re
import smtplib
import ssl
import time
from pathlib import Path
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from email.header import Header
from email.utils import formatdate, make_msgid
from typing import Dict, Any, Optional, List
import logging

from src.config import SMTPConfig
from src.post_formatter import FormattedPost

logger = logging.getLogger(__name__)

class WordPressMailSender:
    """
    Sends posts to WordPress and Google Blogger via Email using standard SMTP.
    Supports Jetpack Post by Email, Postie, standard WP mail receivers,
    and Google Blogger "Post using email" (username.secret@blogger.com),
    including PNG/JPEG illustration attachments generated by Draw Things.
    """

    def __init__(self, config: SMTPConfig):
        self.config = config

    @staticmethod
    def _load_lightweight_image(path: Path, max_bytes: int = 120_000):
        """Returns (bytes, mime_subtype). Converts PNG to a small JPEG so the email stays tiny."""
        raw = path.read_bytes()
        try:
            import io
            from PIL import Image
            img = Image.open(io.BytesIO(raw)).convert("RGB")
            for quality in (82, 72, 62, 50):
                buf = io.BytesIO()
                img.save(buf, "JPEG", quality=quality, optimize=True)
                if buf.tell() <= max_bytes:
                    break
            return buf.getvalue(), "jpeg"
        except Exception as e:
            logger.warning(f"Pillow compression unavailable ({e}); attaching original image.")
            return raw, "png"

    @staticmethod
    def _strip_jetpack_shortcodes(plain_text: str) -> str:
        """Removes Jetpack [category ...], [tags ...], [status ...] shortcodes for Blogger."""
        lines = plain_text.splitlines()
        cleaned = []
        skip_leading_blank = True
        for line in lines:
            if re.match(r"^\[(category|tags|status)\s+.*\]$", line.strip(), flags=re.IGNORECASE):
                continue
            if skip_leading_blank and not line.strip():
                continue
            skip_leading_blank = False
            cleaned.append(line)
        return "\n".join(cleaned)

    @staticmethod
    def _sanitize_html_for_blogger(html_text: str) -> str:
        """
        Simplifies HTML specifically for Blogger's 'Post using email' and strict outbound/inbound SMTP filters:
        1. Replaces <a href="...">text</a> with plain text (eliminates external URL spam-filter triggers while keeping DOI/law references intact).
        2. Safely removes bare URLs without eating adjacent closing HTML tags (</li>, </div>, </p>).
        3. Removes empty <li> / <ul> elements left behind when a bullet contained only a URL.
        4. Converts <table> rows into simple <p> lines and inner <div> blocks into <p> blocks.
        5. Strips inline style="..." and class="..." attributes so only clean, valid semantic tags remain.
        """
        cleaned = html_text
        # 1. Strip <a> tags, keeping inner text
        cleaned = re.sub(r"<a\b[^>]*>(.*?)</a>", r"\1", cleaned, flags=re.IGNORECASE | re.DOTALL)
        # Convert bare DOIs to plain 'DOI: 10.xxxx' and remove remaining bare http/https URLs WITHOUT matching '<' or '>'
        cleaned = re.sub(r"https?://(?:dx\.)?doi\.org/(10\.[^\s<>\"\)\]」』]+)", r"DOI: \1", cleaned)
        cleaned = re.sub(r"https?://[^\s<>\"\)\]」』]+", "", cleaned)

        # 2. Convert <table> blocks into simple paragraphs
        def _table_to_paragraphs(match: re.Match) -> str:
            tbl = match.group(0)
            rows = re.findall(r"<tr\b[^>]*>(.*?)</tr>", tbl, flags=re.IGNORECASE | re.DOTALL)
            p_lines = []
            for row in rows:
                if "<th" in row.lower():
                    continue
                cells = re.findall(r"<td\b[^>]*>(.*?)</td>", row, flags=re.IGNORECASE | re.DOTALL)
                if len(cells) >= 2:
                    k = re.sub(r"<[^>]+>", "", cells[0]).strip()
                    v = cells[1].strip()
                    p_lines.append(f"<p>・<strong>{k}</strong>：{v}</p>")
            return "\n".join(p_lines)

        cleaned = re.sub(r"<table\b[^>]*>.*?</table>", _table_to_paragraphs, cleaned, flags=re.IGNORECASE | re.DOTALL)

        # 3. Replace styled scene divider divs (* * *, ◆ ◆ ◆, or ✦ ✦ ✦) with simple <p>
        cleaned = re.sub(
            r"<div\b[^>]*>\s*(?:\*\s*\*\s*\*|◆\s*◆\s*◆|✦\s*✦\s*✦)\s*</div>",
            "<p>✦ ✦ ✦</p>",
            cleaned,
            flags=re.IGNORECASE
        )

        # 4. Strip outer container div if present, then convert inner <div>...</div> blocks (like numbered list items) into <p>...</p>
        cleaned = re.sub(r"^\s*<div\b[^>]*max-width:\s*820px[^>]*>", "", cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r"<div\b[^>]*>\s*<p\b[^>]*>(.*?)</p>\s*</div>", r"<p>\1</p>", cleaned, flags=re.IGNORECASE | re.DOTALL)
        cleaned = re.sub(r"<div\b[^>]*>(.*?)</div>", r"<p>\1</p>", cleaned, flags=re.IGNORECASE | re.DOTALL)
        cleaned = re.sub(r"</?div\b[^>]*>", "", cleaned, flags=re.IGNORECASE)

        # 5. Strip all inline style/class attributes
        cleaned = re.sub(r'\s+(?:style|class)=["\'][^"\']*["\']', "", cleaned, flags=re.IGNORECASE)

        # 6. Clean up empty <li> items (e.g. "<li></li>" or "<li>URL: </li>" or "<li>e-Gov法令検索: </li>") and empty <ul> blocks
        cleaned = re.sub(
            r"\s*<li>\s*(?:(?:URL|e-Gov法令検索|[^<>]{0,35}(?:Webサイト|公式ページ|リンク|検索))\s*[:：]\s*)?</li>",
            "",
            cleaned,
            flags=re.IGNORECASE
        )
        cleaned = re.sub(r"\s*<ul>\s*</ul>", "", cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r"\s*<p>\s*\*\s*</p>\s*$", "", cleaned, flags=re.IGNORECASE)

        return cleaned.strip()

    BLOGGER_POLICY_DISCLAIMER_PLAIN = (
        "\n\n---\n"
        "※本記事の物語パートに登場する人物名・学校名・団体名・具体的なエピソードはすべて架空のフィクションであり、"
        "実在の個人・学校・機関とは一切関係ありません。解説パートで紹介している教育理論・ICT技術・教育法規は"
        "公的資料および学術文献に基づいています。（Solve School Problems 教育小説アーカイブ）"
    )

    BLOGGER_POLICY_DISCLAIMER_HTML = (
        "\n<hr>\n"
        "<p><small>※本記事の物語パートに登場する人物名・学校名・団体名・具体的なエピソードはすべて架空のフィクションであり、"
        "実在の個人・学校・機関とは一切関係ありません。解説パートで紹介している教育理論・ICT技術・教育法規は"
        "公的資料および学術文献に基づいています。（Solve School Problems 教育小説アーカイブ）</small></p>"
    )

    @classmethod
    def validate_blogger_compliance(cls, post: FormattedPost) -> Dict[str, Any]:
        """
        Verifies that the post complies with Google Blogger's Content Policy & Terms of Service:
        - Non-empty title and educational body within safe size limits
        - No prohibited executable/embed tags (<script>, <iframe>, <object>, <embed>, <form>, javascript:)
        - Clean semantic HTML with fiction/privacy disclaimer
        """
        issues: List[str] = []
        title = (post.title or "").strip()
        if not title:
            issues.append("Post title is empty.")
        raw_html = post.content_html_clean or post.content_html or ""
        if not raw_html.strip():
            issues.append("Post HTML content is empty.")
        if len(raw_html) > 100_000:
            issues.append(f"Post HTML content exceeds safe size limit ({len(raw_html)} chars).")
        if re.search(r"<\s*(?:script|iframe|object|embed|form)\b|javascript:", raw_html, flags=re.IGNORECASE):
            issues.append("Post contains prohibited script/iframe/embed/form tags.")
        return {
            "compliant": len(issues) == 0,
            "issues": issues,
        }

    def create_mime_message(
        self,
        post: FormattedPost,
        recipient: Optional[str] = None,
        is_blogger: bool = False,
        to_email: Optional[str] = None,
        for_blogger: bool = False
    ) -> MIMEMultipart:
        """
        Constructs a MIMEMultipart email message with text, HTML, and optional illustration attachment.
        When is_blogger/for_blogger=True, omits WordPress Jetpack shortcodes ([status], [category], [tags])
        and strips external URLs / complex CSS so outbound/inbound spam filters do not block delivery.
        """
        use_blogger = is_blogger or for_blogger
        target_to = to_email or recipient
        if target_to is None:
            target_to = self.config.blogger_post_email if use_blogger else self.config.wp_post_email
        if target_to and "@blogger.com" in target_to.lower():
            use_blogger = True

        has_image = bool(post.image_path and Path(post.image_path).exists())
        if has_image and use_blogger and os.environ.get(
            "ATTACH_IMAGES_BLOGGER", "true"
        ).strip().lower() not in ("1", "true", "yes"):
            has_image = False

        if has_image:
            msg = MIMEMultipart("mixed")
            alt_part = MIMEMultipart("alternative")
        else:
            msg = MIMEMultipart("alternative")
            alt_part = msg

        # Subject becomes the Post Title on both WordPress and Blogger
        msg["Subject"] = Header(post.title, "utf-8")

        # From header (avoid RFC 2047 encoding if display name is pure ASCII to prevent spam filter penalties)
        try:
            self.config.from_name.encode("ascii")
            from_display = self.config.from_name
        except UnicodeEncodeError:
            from_display = Header(self.config.from_name, "utf-8").encode()
        msg["From"] = f"{from_display} <{self.config.user}>"

        # Destination inbox
        msg["To"] = target_to

        # Standard RFC 5322 Date header; let Gmail SMTP generate its native @mail.gmail.com Message-ID when using smtp.gmail.com
        msg["Date"] = formatdate(localtime=True)
        if "gmail.com" not in (self.config.host or "").lower():
            domain = self.config.user.split("@")[-1] if "@" in self.config.user else "solve-school-problems.local"
            msg["Message-ID"] = make_msgid(domain=domain)

        if use_blogger:
            raw_plain = post.content_plain_clean or self._strip_jetpack_shortcodes(post.content_plain)
            # Strip all raw URLs from the plain-text part
            plain_body = re.sub(r"\[([^\]]+)\]\(https?://[^\)]+\)", r"\1", raw_plain)
            plain_body = re.sub(r"https?://(?:dx\.)?doi\.org/(10\.\S+)", r"DOI: \1", plain_body)
            plain_body = re.sub(r"https?://\S+", "", plain_body)
            if "架空のフィクション" not in plain_body:
                plain_body = plain_body.rstrip() + self.BLOGGER_POLICY_DISCLAIMER_PLAIN
            raw_html = post.content_html_clean or post.content_html
            html_body = self._sanitize_html_for_blogger(raw_html)
            if "架空のフィクション" not in html_body:
                html_body = html_body.rstrip() + self.BLOGGER_POLICY_DISCLAIMER_HTML
        else:
            plain_body = post.content_plain
            html_body = post.content_html

        part_text = MIMEText(plain_body, "plain", "utf-8")
        part_html = MIMEText(html_body, "html", "utf-8")

        alt_part.attach(part_text)
        alt_part.attach(part_html)

        if has_image:
            msg.attach(alt_part)
            img_bytes, subtype = self._load_lightweight_image(Path(post.image_path))
            att_name = f"illustration.{'jpg' if subtype == 'jpeg' else 'png'}"
            img_part = MIMEImage(img_bytes, _subtype=subtype, name=att_name)
            img_part.add_header("Content-Disposition", "attachment", filename=att_name)
            msg.attach(img_part)
            logger.info(f"Attached illustration image: {att_name} ({len(img_bytes)} bytes)")

        return msg

    @staticmethod
    def _parse_email_list(raw_emails: str) -> List[str]:
        if not raw_emails:
            return []
        return [e.strip() for e in raw_emails.split(",") if e.strip()]

    def _send_single_message(self, recipient: str, msg: MIMEMultipart):
        """Sends a single MIME message over a clean SMTP connection."""
        if self.config.use_ssl:
            context = ssl.create_default_context()
            with smtplib.SMTP_SSL(self.config.host, self.config.port, context=context) as server:
                if self.config.user and self.config.password:
                    server.login(self.config.user, self.config.password)
                server.sendmail(self.config.user, [recipient], msg.as_string())
        else:
            with smtplib.SMTP(self.config.host, self.config.port) as server:
                server.ehlo()
                if self.config.use_tls:
                    context = ssl.create_default_context()
                    server.starttls(context=context)
                    server.ehlo()
                if self.config.user and self.config.password:
                    server.login(self.config.user, self.config.password)
                server.sendmail(self.config.user, [recipient], msg.as_string())

    def send_post(
        self,
        post: FormattedPost,
        dry_run: bool = False,
        blogger_only: bool = False
    ) -> Dict[str, Any]:
        """
        Sends the formatted post to WordPress (WP_POST_EMAIL) and simultaneously to Blogger (BLOGGER_POST_EMAIL).
        If blogger_only is True, sends only to Blogger.
        If dry_run is True, skips actual network dispatch and logs details.
        """
        wp_targets = [] if blogger_only else self._parse_email_list(self.config.wp_post_email)
        blogger_targets = self._parse_email_list(self.config.blogger_post_email)
        has_image = bool(post.image_path and Path(post.image_path).exists())

        # Also auto-classify any @blogger.com address placed inside WP_POST_EMAIL
        clean_wp_targets = []
        for addr in wp_targets:
            if "@blogger.com" in addr.lower():
                if addr not in blogger_targets:
                    blogger_targets.append(addr)
            else:
                clean_wp_targets.append(addr)

        if dry_run or not self.config.user or (not clean_wp_targets and not blogger_targets):
            logger.info("================ [DRY RUN / MOCK MODE] ================")
            if not blogger_only:
                logger.info(f"Target WP Email: {self.config.wp_post_email or '(Not Set - WP_POST_EMAIL)'}")
            logger.info(f"Target Blogger Email: {self.config.blogger_post_email or '(Not Set - BLOGGER_POST_EMAIL)'}")
            logger.info(f"Subject (Post Title): {post.title}")
            logger.info(f"From: {self.config.user or '(Not Set - SMTP_USER)'}")
            logger.info(f"Pattern: {post.pattern}")
            logger.info(f"Status: {post.status}")
            logger.info(f"Categories: {', '.join(post.categories)}")
            logger.info(f"Tags: {', '.join(post.tags)}")
            logger.info(f"WP HTML Content Length: {len(post.content_html)} chars")
            logger.info(f"Blogger Clean HTML Content Length: {len(post.content_html_clean or post.content_html)} chars")
            logger.info(f"Illustration Attachment: {post.image_path if has_image else '(None)'}")
            logger.info("========================================================")
            return {
                "success": True,
                "dry_run": True,
                "title": post.title,
                "to": self.config.blogger_post_email if blogger_only else self.config.wp_post_email,
                "blogger_to": self.config.blogger_post_email,
                "image_path": post.image_path if has_image else None,
                "sent_to_wp": False,
                "sent_to_blogger": False,
                "message": "Dry run completed successfully. No actual email sent."
            }

        logger.info(f"Connecting to SMTP server {self.config.host}:{self.config.port}...")

        sent_wp = False
        sent_blogger = False
        sent_blogger_list: List[str] = []
        errors: List[str] = []

        try:
            # 1. Send to WordPress (if not blogger_only and wp_post_email is configured)
            for wp_addr in clean_wp_targets:
                try:
                    wp_msg = self.create_mime_message(post, to_email=wp_addr, for_blogger=False)
                    self._send_single_message(wp_addr, wp_msg)
                    sent_wp = True
                    logger.info(f"Successfully posted to WordPress via email! Recipient: {wp_addr}")
                except Exception as wp_err:
                    err_str = f"{wp_addr}: {wp_err}"
                    logger.error(f"Failed to send email to WordPress ({wp_addr}): {wp_err}", exc_info=True)
                    errors.append(err_str)

            # 2. Send to Blogger over a separate SMTP session (after a 10s pause if WP was just sent)
            for b_addr in blogger_targets:
                try:
                    if sent_wp:
                        time.sleep(10)
                    b_msg = self.create_mime_message(post, to_email=b_addr, for_blogger=True)
                    self._send_single_message(b_addr, b_msg)
                    sent_blogger = True
                    sent_blogger_list.append(b_addr)
                    logger.info(f"Successfully posted to Blogger via email! Recipient: {b_addr}")
                except Exception as b_err:
                    if blogger_only:
                        raise
                    err_str = f"{b_addr}: {b_err}"
                    logger.error(f"Failed to send email to Blogger ({b_addr}): {b_err}", exc_info=True)
                    errors.append(err_str)

            overall_success = sent_wp or sent_blogger
            return {
                "success": overall_success,
                "dry_run": False,
                "title": post.title,
                "to": self.config.blogger_post_email if blogger_only else self.config.wp_post_email,
                "blogger_to": sent_blogger_list,
                "sent_to_wp": sent_wp,
                "sent_to_blogger": sent_blogger,
                "errors": errors,
                "message": f"Post '{post.title}' successfully emailed." if overall_success else "; ".join(errors)
            }
        except Exception as e:
            target_label = "Blogger" if blogger_only else "WordPress/Blogger"
            logger.error(f"Failed to send email to {target_label}: {e}", exc_info=True)
            return {
                "success": False,
                "dry_run": False,
                "title": post.title,
                "to": self.config.blogger_post_email if blogger_only else self.config.wp_post_email,
                "blogger_to": [],
                "sent_to_wp": sent_wp,
                "sent_to_blogger": sent_blogger,
                "error": str(e)
            }
